dev codes for deployment
ml4oncology/model-deployer pull request #1
Opened 2024-03-18 20:27 UTC by MuammarKabirCDI

This is the initial code that supports prediction of ED visit as well as processing data for Symptoms models. Will adapt the Main code for the lgbm model prediction soon.

2024-03-20 18:51 UTC, KevinHeUHN requested changes
Hey Muammar, haven't gone through the preprocess folder yet but I think you can start reading through the other comments and suggestions now. Will finish reviewing the preprocess folder soon. Thanks!

2024-03-20 18:51 UTC, KevinHeUHN commented on Codes/data_prep/src/preprocess/emergency.py
> +    df['event_date'] = pd.to_datetime(df['event_date'])
remove duplicate line

2024-03-20 18:51 UTC, KevinHeUHN commented on Codes/data_prep/combine_features.py
We should combine this file with combine.py

2024-03-25 22:16 UTC, KevinJCHe requested changes

2024-06-27 19:02 UTC, KevinJCHe approved these changes

2024-06-28 18:43 UTC, merged