Minor changes
ml4oncology/model-deployer pull request #5
Opened 2024-10-15 15:58 UTC by MuammarKabirCDI

Changes based on issues with deployed model

2024-10-15 22:51 UTC, KevinHeUHN requested changes
Looking good! Just a couple of nitpicks

2024-10-15 22:51 UTC, KevinHeUHN commented on Codes/data_prep/preprocess/dart.py
> +    # Found one instance of df['patient_ecog']= 'Not Applicable'
I would put this block of code at the beginning of the function actually:

And if its only the one case of 'Not Applicable', we can do this for now

```
mask = df['patient_ecog'].isin(['Not Applicable'])
df.loc[mask, 'patient_ecog'] = None
```
We can add more cases and revise to be more generalizable in the future if necessary.

2024-10-15 22:51 UTC, KevinHeUHN commented on Codes/data_prep/preprocess/lab.py
> +        return f'{number / 2}'
why return as a string? Is all the lab values a string?

2024-10-15 22:51 UTC, KevinHeUHN commented on Codes/data_prep/preprocess/opis.py
> +    dataPull_day = None
try to use snake_case instead of camelCase, for Python best practice

2024-10-15 22:51 UTC, KevinHeUHN commented on Codes/data_prep/preprocess/opis.py
> +    if dataPull_day==None:
small thing, but in Python, we should always do is instead of == when equating None

`if data_pull_day is None:`

2024-10-15 22:51 UTC, KevinHeUHN commented on Codes/data_prep/preprocess/opis.py
> +    if dataPull_day==None:
Could also make this a single line
`trt_date = 'trt_date_utc' if data_pull_day is None else 'tx_sched_date'`

2024-10-16 00:23 UTC, MuammarKabirCDI reviewed
I have modified the codes as requested. Thanks

2024-10-16 14:47 UTC, merged